# HTTP Server
server:
  port: 8888   # HTTP port

# Spring properties
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # uri: file:/home/magonzales/Workshop/LOCAL_REPO_GIT
          uri: https://github.com/miguelgonzales/microservice-config

security:
  user:
    password: mypassword

logging:
  file: logs/${spring.application.name}.log
  level:
    org.springframework.cloud: 'DEBUG'
    com.viajeseci.example: 'DEBUG'